/**
 * Platform Config Generator Service (Sprint 4 - Phase 3)
 * 
 * Generates platform-specific configuration files for iOS, Android, Web, Windows, and macOS
 */

export class PlatformConfigGeneratorService {
  /**
   * Generate iOS configuration files
   */
  generateIOSConfigs(appName: string, bundleId: string): Record<string, string> {
    return {
      'ios/Podfile': this.generateIOSPodfile(appName),
      'ios/Runner/GeneratedPluginRegistrant.swift': this.generateIOSPluginRegistrant(),
      'ios/Runner/Info.plist': this.generateIOSInfoPlist(appName, bundleId),
      'ios/Runner.xcodeproj/project.pbxproj': this.generateIOSXcodeProject(appName),
    };
  }

  /**
   * Generate iOS Podfile
   */
  private generateIOSPodfile(appName: string): string {
    return `platform :ios, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '\$(inherited)',
        'PERMISSION_CAMERA=1',
        'PERMISSION_PHOTOS=1',
        'PERMISSION_LOCATION=1',
      ]
    end
  end
end`;
  }

  /**
   * Generate iOS Info.plist
   */
  private generateIOSInfoPlist(appName: string, bundleId: string): string {
    return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDevelopmentRegion</key>
  <string>\$(DEVELOPMENT_LANGUAGE)</string>
  <key>CFBundleExecutable</key>
  <string>\$(EXECUTABLE_NAME)</string>
  <key>CFBundleIdentifier</key>
  <string>${bundleId}</string>
  <key>CFBundleInfoDictionaryVersion</key>
  <string>6.0</string>
  <key>CFBundleName</key>
  <string>${appName}</string>
  <key>CFBundlePackageType</key>
  <string>APPL</string>
  <key>CFBundleShortVersionString</key>
  <string>\$(FLUTTER_BUILD_VERSION)</string>
  <key>CFBundleSignature</key>
  <string>????</string>
  <key>CFBundleVersion</key>
  <string>\$(FLUTTER_BUILD_NUMBER)</string>
  <key>LSRequiresIPhoneOS</key>
  <true/>
  <key>UILaunchStoryboardName</key>
  <string>LaunchScreen</string>
  <key>UIMainStoryboardFile</key>
  <string>Main</string>
  <key>UISupportedInterfaceOrientations</key>
  <array>
    <string>UIInterfaceOrientationPortrait</string>
    <string>UIInterfaceOrientationLandscapeLeft</string>
    <string>UIInterfaceOrientationLandscapeRight</string>
  </array>
  <key>UISupportedInterfaceOrientationsIPad</key>
  <array>
    <string>UIInterfaceOrientationPortrait</string>
    <string>UIInterfaceOrientationPortraitUpsideDown</string>
    <string>UIInterfaceOrientationLandscapeLeft</string>
    <string>UIInterfaceOrientationLandscapeRight</string>
  </array>
  <key>UIViewControllerBasedStatusBarAppearance</key>
  <false/>
  <key>CADisableMinimumFrameDurationOnPhone</key>
  <true/>
  <key>UIApplicationSupportsIndirectInputEvents</key>
  <true/>
  
  <!-- Permissions -->
  <key>NSCameraUsageDescription</key>
  <string>Camera access is needed to take photos</string>
  <key>NSPhotoLibraryUsageDescription</key>
  <string>Photo library access is needed to select photos</string>
  <key>NSLocationWhenInUseUsageDescription</key>
  <string>Location access is needed for location-based services</string>
</dict>
</plist>`;
  }

  /**
   * Generate iOS Xcode project configuration
   */
  private generateIOSXcodeProject(appName: string): string {
    return `// Generated Xcode project configuration
// This file is automatically generated by Flutter

DEVELOPMENT_TEAM = XXXXXXXXXX;
CODE_SIGN_IDENTITY = "iPhone Developer";
FRAMEWORK_SEARCH_PATHS = \\$(inherited) \\$(FLUTTER_FRAMEWORK_DIR);
LIBRARY_SEARCH_PATHS = \\$(inherited) \\$(FLUTTER_FRAMEWORK_DIR);

/* iOS deployment settings */
IPHONEOS_DEPLOYMENT_TARGET = 11.0;
ENABLE_BITCODE = NO;
`;
  }

  /**
   * Generate iOS plugin registrant
   */
  private generateIOSPluginRegistrant(): string {
    return `//
//  Generated file. Do not edit.
//

import Flutter
import Foundation

func GeneratedPluginRegistrant() {
  // This function is auto-generated by the Flutter build process
  // Add plugins here as they are added to your iOS project
}`;
  }

  /**
   * Generate Android configuration files
   */
  generateAndroidConfigs(appName: string, packageName: string): Record<string, string> {
    return {
      'android/app/build.gradle': this.generateAndroidBuildGradle(packageName),
      'android/gradle.properties': this.generateAndroidGradleProperties(),
      'android/settings.gradle': this.generateAndroidSettingsGradle(),
      'android/app/src/main/AndroidManifest.xml': this.generateAndroidManifest(appName, packageName),
    };
  }

  /**
   * Generate Android build.gradle
   */
  private generateAndroidBuildGradle(packageName: string): string {
    return `apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "\$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 33
    ndkVersion "25.1.8937393"

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        applicationId "${packageName}"
        minSdkVersion 21
        targetSdkVersion 33
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            signingConfig signingConfigs.debug
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            debuggable true
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:\$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test:runner:1.5.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}`;
  }

  /**
   * Generate Android gradle.properties
   */
  private generateAndroidGradleProperties(): string {
    return `org.gradle.jvmargs=-Xmx4096m
android.useAndroidX=true
android.enableJetifier=true
android.enableDexingArtifactTransform=false
android.gradle.plugin.compile.classpath.check=false`;
  }

  /**
   * Generate Android settings.gradle
   */
  private generateAndroidSettingsGradle(): string {
    return `include ':app'

def flutterProjectRoot = rootProject.projectDir.parentFile.toPath()

def plugins = new Properties()
def pluginsFile = new File(flutterProjectRoot.toFile(), '.flutter-plugins')
if (pluginsFile.exists()) {
    pluginsFile.withInputStream { stream -> plugins.load(stream) }
}

plugins.each { name, path ->
    def pluginDirectory = flutterProjectRoot.resolve(path).resolve('android').toFile()
    include ":\$name"
    project(":\$name").projectDir = pluginDirectory
}`;
  }

  /**
   * Generate Android AndroidManifest.xml
   */
  private generateAndroidManifest(appName: string, packageName: string): string {
    return `<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="${packageName}">
   
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

    <application
        android:label="${appName}"
        android:icon="@mipmap/ic_launcher"
        android:usesCleartextTraffic="true"
        android:supportsRtl="true">
        
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>`;
  }

  /**
   * Generate Web configuration files
   */
  generateWebConfigs(appName: string): Record<string, string> {
    return {
      'web/index.html': this.generateWebIndexHtml(appName),
      'web/manifest.json': this.generateWebManifest(appName),
      'web/favicon.png': '[Base64 PNG Data]',
    };
  }

  /**
   * Generate Web index.html
   */
  private generateWebIndexHtml(appName: string): string {
    return `<!DOCTYPE html>
<html>
  <head>
    <base href="/">
    <meta charset="UTF-8">
    <meta content="IE=Edge" http-equiv="X-UA-Compatible">
    <meta name="description" content="A new Flutter application.">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="${appName}">
    <link rel="apple-touch-icon" href="/icons/Icon-192.png">
    <link rel="icon" type="image/png" href="/favicon.png"/>
    <title>${appName}</title>
    <link rel="manifest" href="/manifest.json">
    <link rel="stylesheet" type="text/css" href="/flutter.css">
    <script defer src="/flutter.js"></script>
  </head>
  <body>
    <script>
      window.addEventListener('flutter-initialized', function() {
        console.log('Flutter application initialized');
      });
    </script>
  </body>
</html>`;
  }

  /**
   * Generate Web manifest.json
   */
  private generateWebManifest(appName: string): string {
    return `{
  "name": "${appName}",
  "short_name": "${appName}",
  "start_url": "/",
  "display": "standalone",
  "background_color": "#ffffff",
  "theme_color": "#2196F3",
  "description": "A new Flutter application",
  "orientation": "portrait-primary",
  "icons": [
    {
      "src": "/icons/Icon-192.png",
      "sizes": "192x192",
      "type": "image/png"
    },
    {
      "src": "/icons/Icon-512.png",
      "sizes": "512x512",
      "type": "image/png"
    },
    {
      "src": "/icons/Icon-maskable-192.png",
      "sizes": "192x192",
      "type": "image/png",
      "purpose": "maskable"
    },
    {
      "src": "/icons/Icon-maskable-512.png",
      "sizes": "512x512",
      "type": "image/png",
      "purpose": "maskable"
    }
  ]
}`;
  }

  /**
   * Generate Windows configuration files
   */
  generateWindowsConfigs(appName: string, packageName: string): Record<string, string> {
    return {
      'windows/runner/main.cpp': this.generateWindowsMainCpp(appName),
      'windows/runner/CMakeLists.txt': this.generateWindowsCMakeLists(appName),
    };
  }

  /**
   * Generate Windows main.cpp
   */
  private generateWindowsMainCpp(appName: string): string {
    return `#include <flutter/dart_project.h>
#include <flutter/flutter_view_controller.h>
#include <windows.h>

#include "utils.h"

int APIENTRY wWinMain(_In_ HINSTANCE instance, _In_opt_ HINSTANCE prev,
                      _In_ wchar_t *command_line, _In_ int show_command) {
  // Attach console on build and stderr so cout, cerr, clog can output to it.
  if (AttachConsole(ATTACH_PARENT_PROCESS)) {
    freopen("CONOUT\$", "w", stdout);
    freopen("CONOUT\$", "w", stderr);
    fprintf(stderr, "Visual Studio output window\\n");
  }

  // Initialize COM on the main thread.
  CoInitializeEx(nullptr, COINIT_APARTMENTTHREADED);

  flutter::DartProject project(L"data");

  std::vector<std::string> command_line_arguments =
      GetCommandLineArguments();

  project.set_dart_entrypoint_arguments(std::move(command_line_arguments));

  flutter::FlutterViewController controller(project);

  // Runs the Flutter application and returns when it ends.
  int result = controller.RunEventLoopWithWindowExit();

  CoUninitialize();

  return result;
}`;
  }

  /**
   * Generate Windows CMakeLists.txt
   */
  private generateWindowsCMakeLists(appName: string): string {
    return `cmake_minimum_required(VERSION 3.14)
project(${appName.toLowerCase().replace(/\s+/g, '_')} LANGUAGES CXX)

set(BINARY_NAME "${appName}")

cmake_policy(SET CMP0063 NEW)

set(CMAKE_CXX_VISIBILITY_PRESET hidden)
set(CMAKE_VISIBILITY_INLINES_HIDDEN ON)

# Root filesystem for source tree.
set(FLUTTER_SOURCE_DIR "\${CMAKE_CURRENT_SOURCE_DIR}/flutter")
set(FLUTTER_MANAGED_DIR "\${FLUTTER_SOURCE_DIR}/ephemeral")

# Architecture check
get_filename_component(FLUTTER_MANAGED_DIR "\${FLUTTER_SOURCE_DIR}/ephemeral" ABSOLUTE)

# Flutter library directory
set(FLUTTER_LIB_DIR "\${FLUTTER_MANAGED_DIR}/flutter_windows/Debug")

# Source files
set(SOURCES
  "runner.cpp"
  "main.cpp"
  "utils.cpp"
)

add_executable(\${BINARY_NAME} WIN32 \${SOURCES})

# Link Flutter libraries
target_link_libraries(\${BINARY_NAME} PRIVATE flutter flutter_windows)`;
  }

  /**
   * Generate macOS configuration files
   */
  generateMacOSConfigs(appName: string, bundleId: string): Record<string, string> {
    return {
      'macos/Runner/Info.plist': this.generateMacOSInfoPlist(appName, bundleId),
      'macos/Runner/GeneratedPluginRegistrant.swift': this.generateMacOSPluginRegistrant(),
    };
  }

  /**
   * Generate macOS Info.plist
   */
  private generateMacOSInfoPlist(appName: string, bundleId: string): string {
    return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDevelopmentRegion</key>
  <string>en</string>
  <key>CFBundleExecutable</key>
  <string>\$(EXECUTABLE_NAME)</string>
  <key>CFBundleIdentifier</key>
  <string>${bundleId}</string>
  <key>CFBundleInfoDictionaryVersion</key>
  <string>6.0</string>
  <key>CFBundleName</key>
  <string>${appName}</string>
  <key>CFBundlePackageType</key>
  <string>APPL</string>
  <key>CFBundleShortVersionString</key>
  <string>\$(FLUTTER_BUILD_VERSION)</string>
  <key>CFBundleVersion</key>
  <string>\$(FLUTTER_BUILD_NUMBER)</string>
  <key>LSMinimumSystemVersion</key>
  <string>10.13</string>
  <key>NSHumanReadableCopyright</key>
  <string>Copyright © 2024</string>
  <key>NSMainNibFile</key>
  <string>MainMenu</string>
  <key>NSPrincipalClass</key>
  <string>NSApplication</string>
</dict>
</plist>`;
  }

  /**
   * Generate macOS plugin registrant
   */
  private generateMacOSPluginRegistrant(): string {
    return `//
//  Generated file. Do not edit.
//

import Foundation

func GeneratedPluginRegistrant() {
  // This function is auto-generated by the Flutter build process
  // Add plugins here as they are added to your macOS project
}`;
  }

  /**
   * Generate Linux configuration files
   */
  generateLinuxConfigs(appName: string): Record<string, string> {
    return {
      'linux/my_application.cc': this.generateLinuxApplicationCC(appName),
      'linux/CMakeLists.txt': this.generateLinuxCMakeLists(appName),
    };
  }

  /**
   * Generate Linux application.cc
   */
  private generateLinuxApplicationCC(appName: string): string {
    return `#include "my_application.h"
#include <gtk/gtk.h>

struct _MyApplication {
  GtkApplication parent_instance;
  char** dart_entrypoint_arguments;
};

G_DEFINE_TYPE(MyApplication, my_application, GTK_TYPE_APPLICATION)

// Implements GApplication::activate.
static void my_application_activate(GApplication* application) {
  MyApplication* self = MY_APPLICATION(application);
  GtkWindow* window =
      GTK_WINDOW(gtk_application_window_new(GTK_APPLICATION(application)));

  // Use a header bar when running in GNOME as this is the common case when
  // developing GNOME applications, and using a header bar is the setup most
  // Internet discussion about using Gtk in Flutter development suggests.
  gboolean use_header_bar = TRUE;
  if (gtk_settings_get_default() != nullptr) {
    g_object_get(gtk_settings_get_default(), "gtk-shell-shows-app-menu",
                 &use_header_bar, nullptr);
  }

  gtk_window_set_title(window, "${appName}");
  gtk_window_set_default_size(window, 1280, 720);
  gtk_widget_show(GTK_WIDGET(window));

  fl_register_plugins(FL_ENGINE(fl_view_get_engine(FL_VIEW(gtk_bin_get_child(GTK_BIN(window))))));

  g_autoptr(FlDartProject) project = fl_dart_project_new();
  fl_dart_project_set_dart_entrypoint_arguments(
      project, self->dart_entrypoint_arguments);

  g_autoptr(FlView) view = fl_view_new(project);
  gtk_widget_show(GTK_WIDGET(view));
  gtk_container_add(GTK_CONTAINER(window), GTK_WIDGET(view));

  gtk_widget_grab_focus(GTK_WIDGET(view));
}`;
  }

  /**
   * Generate Linux CMakeLists.txt
   */
  private generateLinuxCMakeLists(appName: string): string {
    return `cmake_minimum_required(VERSION 3.10)
project(${appName.toLowerCase().replace(/\s+/g, '_')} LANGUAGES CXX)

set(PROJECT_VERSION "1.0.0")

set(BINARY_NAME "${appName}")

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

find_package(PkgConfig REQUIRED)
pkg_check_modules(GTK gtk+-3.0 REQUIRED)

set(SOURCES
  "my_application.cc"
  "main.cc"
)

add_executable(\${BINARY_NAME} \${SOURCES})
target_include_directories(\${BINARY_NAME} PRIVATE "\${CMAKE_CURRENT_SOURCE_DIR}")
target_link_libraries(\${BINARY_NAME} PRIVATE \${GTK_LIBRARIES})
target_include_directories(\${BINARY_NAME} PRIVATE \${GTK_INCLUDE_DIRS})
target_compile_options(\${BINARY_NAME} PRIVATE \${GTK_CFLAGS_OTHER})`;
  }

  /**
   * Validate platform configuration
   */
  validatePlatformConfig(platform: string, config: string): string[] {
    const errors: string[] = [];

    switch (platform.toLowerCase()) {
      case 'android':
        if (!config.includes('AndroidManifest.xml')) {
          errors.push('Missing AndroidManifest.xml configuration');
        }
        if (!config.includes('build.gradle')) {
          errors.push('Missing build.gradle configuration');
        }
        break;

      case 'ios':
        if (!config.includes('Info.plist')) {
          errors.push('Missing Info.plist configuration');
        }
        if (!config.includes('Podfile')) {
          errors.push('Missing Podfile configuration');
        }
        break;

      case 'web':
        if (!config.includes('index.html')) {
          errors.push('Missing index.html');
        }
        if (!config.includes('manifest.json')) {
          errors.push('Missing manifest.json');
        }
        break;

      default:
        errors.push(`Unknown platform: ${platform}`);
    }

    return errors;
  }
}
